<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.common.services</groupId>
        <artifactId>postcards</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>postcards-services-producer</artifactId>
    <name>postcards-services-producer</name>
    <description>Message producer services for async processing</description>

    <dependencies>
        <dependency>
            <groupId>org.common.services</groupId>
            <artifactId>postcards-application-services-apis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.common.services</groupId>
            <artifactId>postcards-domain-services</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
