<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.vs.common.services</groupId>
        <artifactId>group-build-aggregator</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>org.vs.common.services.basic.elements</groupId>
    <artifactId>common-basic-elements</artifactId>
    <packaging>pom</packaging>

    <modules>
        <!--   LEVEL01    -->
        <module>common-model-universal</module>

        <!--  LEVEL02 -->
        <module>common-model-persistence-records</module>
        <module>common-model-application-dtos</module>

        <!--  LEVEL03 -->
        <module>common-model-converters</module>

        <!--  LEVEL04 -->
        <module>common-persistence-accessors</module>

        <!--  LEVEL05 -->
        <module>common-domain-services</module>

        <!--  LEVEL06 -->
        <module>common-application-services</module>
        <module>common-application-ui</module>

        <!--  LEVEL07 -->
        <module>common-application-porter</module>
        <module>common-application-web</module>

    </modules>

    <properties>
        <spring-boot.repackage.skip>true</spring-boot.repackage.skip>
    </properties>

</project>