spring.application.name=special-cards-reader

server.port=8080

#Security
# Set global session timeout (optional, redundant with setMaxInactiveInterval)
server.servlet.session.timeout=75m
#server.servlet.session.timeout=3m

# Enable multipart file uploads
spring.servlet.multipart.enabled=true
# Max file size (example: 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web=DEBUG


#Access logs config
server.tomcat.accesslog.enabled=true
#server.tomcat.accesslog.directory=D:/logs/active/cards/access
#server.tomcat.accesslog.directory=/var/logs/active/cards/access
server.tomcat.accesslog.directory=/home/logs/active/cards/access
server.tomcat.accesslog.prefix=access
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D

logging.file.path=/home/logs/active/cards/app



spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=true


#spring.datasource.url=jdbc:h2:file:./src/main/resources/database/h2/data/events_organization_db
#
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=sa
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
##spring.h2.console.settings.trace=false
#spring.jpa.properties.hibernate.hbm2ddl.auto=update





